import '../assets/styles/index.scss';
import './components/tabs';
import './components/smothScroll';
import './components/validationInput';
import './components/poppup';
import './components/checkbox';
import './components/radio';
import './components/accordion';
import './page/welcome';
